site_name: Words of Power Editor
repo_url: https://github.com/texnoforge/wopeditor/
nav:
  - README.md
  - intro.md
  - install.md
  - core_symbols.md
markdown_extensions:
  - admonition
  - toc:
      permalink: True
theme:
  name: material
  logo: img/x.png
  palette:
    scheme: slate
    primary: black
    accent: cyan
